"""Dimensionality reduction projection model.

Classes:
    Projection: Stores 2D and 3D coordinates generated by UMAP/t-SNE for each response.
"""

from __future__ import annotations

from typing import Optional
from uuid import UUID

from sqlalchemy import UniqueConstraint
from sqlmodel import Field, SQLModel


class Projection(SQLModel, table=True):
    __tablename__ = "projections"
    __table_args__ = (
        UniqueConstraint("response_id", "method", "dim", name="uq_projection_response_method_dim"),
    )

    id: Optional[int] = Field(default=None, primary_key=True)
    response_id: UUID = Field(foreign_key="responses.id")
    method: str
    dim: int
    x: float
    y: float
    z: Optional[float] = None


